title: Kuarnty's Blog
description: A blog about Computer Science and Mathematics
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

show_downloads: false

github:
  is_project_page: false